# Generated by Django 4.1.2 on 2023-06-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='parent',
        ),
    ]
