# Generated by Django 4.1.2 on 2023-06-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_commentmodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='user',
        ),
    ]
